name: 'Angular Build and Test'
description: 'Builds the Angular project and runs tests'
inputs:
  node-version:
    description: 'Version of Node.js to use'
    required: false
    default: '22.11.0'
  npm-token:
    description: 'NPM authentication token'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Configure npm authentication
      run: echo "//registry.npmjs.org/:_authToken=${{ inputs.npm-token }}" > ~/.npmrc
      shell: bash

    - name: Install dependencies
      run: npm install
      shell: bash

    - name: Build Angular project
      run: npm run build
      shell: bash

    - name: Run tests
      run: npm run test
      shell: bash
