# name: Build and Deploy Angular App to GitHub Pages

# on:
#   push:
#     branches:
#       - main  # oder 'master' oder dein Hauptbranch
# permissions:
#   actions: write
#   contents: write
# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
    
    
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - name: Set up Node
#         uses: actions/setup-node@v3
#         with:
#           node-version: 18  # oder 18, je nach Bedarf

#       - name: Install dependencies
#         run: npm ci
#         # Anstelle von 'npm install' kann man 'npm ci' für einen reproduzierbaren Build verwenden.

#       - name: Build Angular App
#         run: npm run build -- --base-href /actions-test/
#         # oder: npx ng build --configuration production
#         # Wichtig: Stelle sicher, dass in der Angular CLI-Konfiguration outputPath = dist/<projekt-name> ist.

#       - name: Deploy to GitHub Pages
#         uses: JamesIves/github-pages-deploy-action@v4.4.1
#         with:
#           branch: gh-pages            # Zielbranch für GitHub Pages
#           folder: dist/my-standalone-app/browser # Pfad zum generierten Build-Ordner
#           clean: true                 # Löscht alle vorherigen Inhalte in gh-pages


name: Build and Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - main  # oder 'master' oder Ihr Hauptbranch
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # oder eine andere benötigte Version

      - name: Install Dependencies
        run: npm ci

      - name: Build Angular App
        run: npm run build
        # Stellen Sie sicher, dass der outputPath in der angular.json korrekt eingestellt ist

      - name: Upload Build Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/my-standalone-app/browser  # Pfad zum generierten Build-Ordner

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
