name: Build and Test Angular Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Angular Build and Test
        uses: ./.github/actions/angular-build-test
        with:
          node-version: '16'
