name: Build and Test Angular Project
run-name: Build ${{ github.run_number }}
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
permissions:
  actions: write
  contents: read
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Workflow Runs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: get_runs
        run: |
          # Hol die letzten 20 Workflow-Runs (Pagination möglich)
          response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/runs)

          # Filtere die Workflow-IDs aus der API-Antwort
          echo "$response" | jq -r '.workflow_runs | sort_by(.run_number) | .[:-5] | .[].id' > old_runs.txt

      - name: Delete Old Workflow Runs
        if: success()
        run: |
          # Lösche jeden alten Run
          while read -r run_id; do
            curl -X DELETE -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id
          done < old_runs.txt

  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Schritt 1: Repository auschecken
      - name: Checkout repository
        uses: actions/checkout@v3

      # Schritt 2: Angular Build und Test ausführen
      - name: Angular Build and Test
        uses: ./.github/actions/angular-build-test
        with:
          node-version: '22.11.0'
          npm-token: ${{ secrets.NPM_TOKEN }}